### ISSUE TITLE
Makecode Arcade Discord Invite

### ISSUE THREAD

**Issue by Brohann3214** [PatchesDog/still-havent-decided-on-a-name-yet#1]
Idk if you have discord but we decided to invite you anyway
https://discord.gg/f5EF6rs6
https://discord.gg/yTFvxeu5
(yea there's 2)

sorry for such an off-topic issue

**Comment by PatchesDog** [comment]
Hellooo! The invite is invalid, can you resend

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
Virus-free.www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by PatchesDog** [comment]
nvm
